### ISSUE TITLE
Failed to connect to database

### ISSUE THREAD

**Issue by chenming9453** [AnaBVA/PulmonDB#1]
Hi, I am trying to download the data through the R package. However, I got this error message:

Connecting to PulmonDB
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Host '10.200.0.254' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'

for every commend I used. I am wondering how to solve this. Thanks!

**Comment by AnaBVA** [comment]
Thank you so much for reporting the error. 
I solved it but it may come back. Can you please reinstall the package? 
`remotes::install_github("AnaBVA/PulmonDB",build_vignettes = F)`
 
I'm working on a permanent solution but don't hesitate to open it again if it is needed.
