### ISSUE TITLE
Errors in downloading data

### ISSUE THREAD

**Issue by SCarello8** [AnaBVA/PulmonDB#2]
Hi, 
I would like to download some data through the R package, but I got two different error messages.
For example, for GSE37147:

Connecting to PulmonDB
Error in suppressMessages(., dplyr::summarise(dplyr::first(platform_name),  : 
  unused argument (dplyr::summarise(dplyr::first(platform_name), dplyr::first(experiment_access_id)))

and, for instance, for GSE87098:

Connecting to PulmonDB
Error: Assigned data `value` must be compatible with existing data.
ℹ Error occurred for column `162`.
x Can't convert character to double.

Thank you!

**Comment by SCarello8** [comment]
I solved the first problem embedding the entire pipe "cascade" into the suppressMessages() function at row 202 of annotationPulmonDB() and I solved the second one forcing the columns of ref and con tibbles to be characters after row 179 of annotationPulmonDB().

**Comment by SebNickel** [comment]
@SCarello8 
I could replicate your second issue but not the first one.
I hope to submit a pull request within the next week. Hopefully it will include a fix to your issues.
Thanks for flagging this.

**Comment by AnaBVA** [comment]
I'm sorry for the late response! 
@SebNickel Thanks, I'll wait for your pull request.

@SCarello8 Do you have any other problems? Thanks for your patient
