### ISSUE TITLE
Problem with accessing the database

### ISSUE THREAD

**Issue by chenming9453** [AnaBVA/PulmonDB#3]
Hi when I used to be able to access the R package and database. However, when I tried to access it today, I got the error message:

Failed to connect to database: Error: Host '10.200.0.254' is blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'

I am wondering how can I solve this problem. Thanks!

**Comment by ChelseaCHENX** [comment]
Hi there! I have got similar issue - I get 404 error at http://pulmondb.liigh.unam.mx/ 
It is a very great gathering of data and appreciate it a lot for you guys - hopefully it will be solved soon - please keep us informed :)

**Comment by AnaBVA** [comment]
Hello everyone! 

I'm so sorry for the late response, I didn't turn on the notifications so I wasn't aware of these issues. I solved the `Error: Host '10.200.0.254'` and checked it. Now `genesPulmonDB(c("MMP1","JUND"),"GSE1122")` is running without a problem from my side. 

Please try it again and let me know if you had any other issue (Notification are turned on). Thank you!

**Comment by AnaBVA** [comment]
@ChelseaCHENX I think the error 404 error at http://pulmondb.liigh.unam.mx/ is also solved. Demo is working now
